[versions]
agp = "8.3.2"
kotlin = "2.1.0"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
playServicesLocation = "21.2.0"
firebaseFirestoreV = "25.0.0"
maps = "18.2.0"
lifecycle = "2.8.7"

googleServicesVersion = "4.4.3"
retrofitVersion = "2.9.0"
retrofitgsonVersion= "2.9.0"
okhttp = "4.12.0"
coroutines = "1.8.1"
navigationFragmentKtx = "2.9.3"
navigationUiKtx = "2.9.3"
firebaseAuth = "24.0.1"
firebaseDatabase = "22.0.0"
loginGoogleV = "21.4.0"
glideV = "4.16.0"
ccpV = "2.7.0"
circleImagenV = "3.1.0"
firebaseStorageV = "22.0.0"
cardview = "1.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

retrofit = {module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion"}
retrofit-converter-gson = {module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitgsonVersion"}
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
firebaseAuth = {group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth"}
firebaseDatabase = {group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase"}
loginGoogle = {group = "com.google.android.gms", name = "play-services-auth", version.ref= "loginGoogleV"}
glide = {group = "com.github.bumptech.glide", name = "glide", version.ref = "glideV"}
ccp = {group = "com.hbb20", name = "ccp", version.ref = "ccpV"}
circleImage = {group = "de.hdodenhof", name = "circleimageview", version.ref = "circleImagenV"}
firebaseStorage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebaseStorageV" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
firebaseFirestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestoreV" }
google-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "maps" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleService = { id = "com.google.gms.google-services", version.ref = "googleServicesVersion"}

